---
title: final_story_idea
output: html_document
date: "June 7, 2025"
---

## The Trump administration's trade war and the promotional products industry 

### Story pitch memo

Olivia Borgula
oborgula@terpmail.umd.edu | 616-970-3620
June 2, 2025

<b>How Trump’s trade war will affect the promotional products industry</b>

<b>Why this story:</b> T-shirts are consistently a top promotional product. U.S. President Donald Trump has levied heavy tariffs since taking office in January on countries including China — which is a top exporter of cotton T-shirts to the U.S. — resulting in steeper prices and a blow to the promotional product industry.  

The Trump administration’s trade war is relevant in the current political climate and has a direct tie to ASI’s coverage because it targets items and generally has led to cost increases. While tariffs have wide-reaching effects on the promotional product industry, this story may encourage manufacturers to be more creative outside of T-shirts for their promotional products or seek domestic sellers. 

<b>Audience:</b> This story’s audience would be stakeholders in the promotional products industry, especially those who sell T-shirts or are interested in staying up-to-date about tariff developments. I can interview industry experts, T-shirt manufacturers and economic experts with expertise on how tariffs work.

ASI has covered tariffs extensively, but the bulk of coverage is breaking news stories or research about stakeholder opinions on tariffs and their general implication for the industry. There has not been a fleshed out, data-driven story like the one I’m proposing and there has not been in-depth coverage on how a specific promotional product will be affected, like T-shirts.  

<b>Data, visuals and graphics:</b> I will analyze data from the International Trade Association — which tracks U.S. textile and apparel imports by country — to determine top countries that import materials of interest based on what I’ve researched about promotional T-shirts: cotton T-shirts and polyester filament fabrics. I’m interested in data quantifying the number of shirts imported from other countries, rather than imports on the raw materials, because promotional T-shirts tend to be shipped from other countries rather than made domestically. 

I’ll also find how much money the U.S. spent on these imports from the top countries and how much cotton and polyester T-shirt imports have changed over time by using another data tool from the International Trade Association. 

For data on T-shirts as a promotional product, I’ll use ASI’s market research to explore what the total promotional T-shirt sales were in 2024 — the most recent data — and whether that’s changed over the last five to 10 years by examining past state of the industries. 

For visuals, I plan on creating a map in Flourish showing the flow of cotton T-shirt imports from top countries outside the U.S. with the weight of the line representing the total monetary value of the transaction. I also want to create additional Flourish graphics like bar charts, line charts and potentially an alluvial diagram to compare imports across countries and over time. I prefer Flourish over ggplot or Datawrapper because it’s the site I’m most familiar with and I want interactive graphics on the final markdown presentation. 

<b>Other information I’ll need:</b> I want to do additional data analysis for secondary imported materials in promotional T-shirts, like polyester shirts and textiles, and will do additional research on how tariffs will affect the cost of these goods. 

<b>Estimated delivery:<b> mid to late June. 


```{r include=FALSE}
#load in libraries 
library(tidyverse)
library(janitor)
library(readxl)
library(rvest)
```


